# Generated by Django 5.2.8 on 2025-11-06 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('producao_semanal_desejada', models.FloatField(help_text='Producao semanal desejada (kg ou unidades)')),
                ('num_modulos', models.IntegerField(help_text='Numero de modulos de cultivo')),
                ('area_total_hortalica', models.FloatField(blank=True, help_text='Area total ocupada por esta hortalica (m2)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hortalica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_plantio', models.CharField(choices=[('mudas', 'Mudas'), ('direta', 'Semeadura Direta')], max_length=20)),
                ('ciclo_desenvolvimento', models.IntegerField(default=0, help_text='Semanas de desenvolvimento')),
                ('ciclo_colheita', models.IntegerField(help_text='Semanas de colheita')),
                ('ciclo_limpeza', models.IntegerField(help_text='Semanas para limpeza/preparo')),
                ('espacamento_linhas', models.FloatField(help_text='Espacamento entre linhas (m)')),
                ('espacamento_plantas', models.FloatField(help_text='Espacamento entre plantas (m)')),
                ('produtividade_esperada', models.FloatField(default=0, help_text='Produtividade esperada por modulo (kg ou unidades)')),
                ('area_modulo', models.FloatField(help_text='Area de cada modulo (m2)')),
                ('periodicidade', models.IntegerField(help_text='Intervalo entre plantios (semanas)')),
            ],
        ),
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade_colhida', models.FloatField(default=0, help_text='Quantidade colhida (kg ou unidades)')),
                ('cultivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='Horta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('localizacao', models.CharField(blank=True, max_length=150, null=True)),
                ('area_total', models.FloatField(blank=True, help_text='Area total da horta em m2', null=True)),
                ('consumo_agua_estimado', models.FloatField(blank=True, help_text='Consumo estimado de agua (m3/mes)', null=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cultivo',
            name='horta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horta'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='hortalica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hortalica'),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('total_produzido_planejado', models.FloatField(help_text='Producao total planejada (kg ou unidades)')),
                ('total_colhido_real', models.FloatField(default=0, help_text='Producao total colhida (kg ou unidades)')),
                ('eficiencia', models.FloatField(blank=True, help_text='Eficiencia de producao (%)', null=True)),
                ('horta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horta')),
            ],
        ),
    ]
