# Generated by Django 4.2.11 on 2025-10-03 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hortaliça',
            name='ciclo',
        ),
        migrations.RemoveField(
            model_name='hortaliça',
            name='espacamento',
        ),
        migrations.RemoveField(
            model_name='hortaliça',
            name='produtividade',
        ),
        migrations.AddField(
            model_name='hortaliça',
            name='area_modulo',
            field=models.FloatField(default=1, help_text='Área de cada módulo (m²)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hortaliça',
            name='ciclo_colheita',
            field=models.IntegerField(default=1, help_text='Semanas de colheita'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hortaliça',
            name='ciclo_limpeza',
            field=models.IntegerField(default=1, help_text='Semanas para limpeza/preparo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hortaliça',
            name='espacamento_linhas',
            field=models.FloatField(default=1, help_text='Espaçamento entre linhas (m)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hortaliça',
            name='espacamento_plantas',
            field=models.FloatField(default=1, help_text='Espaçamento entre plantas (m)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hortaliça',
            name='num_modulos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hortaliça',
            name='periodicidade',
            field=models.IntegerField(default=1, help_text='Intervalo entre plantios (semanas)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hortaliça',
            name='plantas_por_modulo',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hortaliça',
            name='tipo_plantio',
            field=models.CharField(choices=[('mudas', 'Mudas'), ('direta', 'Semeadura Direta')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producao_semanal', models.FloatField()),
                ('unidade', models.CharField(help_text='Ex: kg, cabeças, unidades', max_length=20)),
                ('horta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horta')),
                ('hortaliça', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hortaliça')),
            ],
        ),
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('quantidade', models.FloatField()),
                ('producao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producao')),
            ],
        ),
    ]
