# Generated by Django 5.2.7 on 2025-10-22 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_hortaliça_ciclo_remove_hortaliça_espacamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('total_produzido', models.FloatField(help_text='Total produzido planejado (kg)')),
                ('total_colhido', models.FloatField(help_text='Total colhido real (kg)')),
                ('consumo_agua', models.FloatField(help_text='Consumo de água (m³)')),
                ('eficiencia', models.FloatField(blank=True, help_text='Eficiência de produção (%)', null=True)),
                ('horta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horta')),
            ],
        ),
    ]
