# Generated by Django 5.2.8 on 2025-11-06 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_relatorio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colheita',
            name='producao',
        ),
        migrations.RemoveField(
            model_name='colheita',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='horta',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='hortaliça',
            name='num_modulos',
        ),
        migrations.RemoveField(
            model_name='hortaliça',
            name='plantas_por_modulo',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='consumo_agua',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='total_colhido',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='total_produzido',
        ),
        migrations.AddField(
            model_name='colheita',
            name='quantidade_colhida',
            field=models.FloatField(default=0, help_text='Quantidade colhida (kg ou unidades)'),
        ),
        migrations.AddField(
            model_name='horta',
            name='area_total',
            field=models.FloatField(blank=True, help_text='Área total da horta em m²', null=True),
        ),
        migrations.AddField(
            model_name='horta',
            name='consumo_agua_estimado',
            field=models.FloatField(blank=True, help_text='Consumo estimado de água (m³/mês)', null=True),
        ),
        migrations.AddField(
            model_name='horta',
            name='localizacao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='hortaliça',
            name='ciclo_desenvolvimento',
            field=models.IntegerField(default=0, help_text='Semanas de desenvolvimento'),
        ),
        migrations.AddField(
            model_name='hortaliça',
            name='produtividade_esperada',
            field=models.FloatField(default=0, help_text='Produtividade esperada por módulo (kg ou unidades)'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='total_colhido_real',
            field=models.FloatField(default=0, help_text='Produção total colhida (kg ou unidades)'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='total_produzido_planejado',
            field=models.FloatField(default=1, help_text='Produção total planejada (kg ou unidades)'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('producao_semanal_desejada', models.FloatField(help_text='Produção semanal desejada (kg ou unidades)')),
                ('num_modulos', models.IntegerField(help_text='Número de módulos de cultivo')),
                ('area_total_hortaliça', models.FloatField(blank=True, help_text='Área total ocupada por essa hortaliça (m²)', null=True)),
                ('horta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horta')),
                ('hortaliça', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hortaliça')),
            ],
        ),
        migrations.AddField(
            model_name='colheita',
            name='cultivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cultivo'),
        ),
        migrations.DeleteModel(
            name='Producao',
        ),
    ]
